"""Project invariants that must not be supplied by a user or environment variable."""

ASSESSMENT_NUMBER = "+18054398008"
LIVE_CALL_ACKNOWLEDGEMENT = "I_UNDERSTAND_THIS_PLACES_A_PAID_CALL"
DEFAULT_CALL_TIME_LIMIT_SECONDS = 240
MIN_CALL_TIME_LIMIT_SECONDS = 60
MAX_CALL_TIME_LIMIT_SECONDS = 240
